<?php

return [

    /*
    |--------------------------------------------------------------------------
    | OpenAPI Specification Metadata
    |--------------------------------------------------------------------------
    */
    'openapi' => [
        'title' => env('LIVEAPI_TITLE', config('app.name').' API'),
        'description' => env('LIVEAPI_DESCRIPTION', 'Generated by Laravel LiveApi'),
        'version' => env('LIVEAPI_VERSION', '1.0.0'),
        'base_url' => env('LIVEAPI_BASE_URL', config('app.url')),
        'security_scheme' => 'Sanctum', // OpenAPI security scheme name
    ],

    /*
    |--------------------------------------------------------------------------
    | Capture Control
    |--------------------------------------------------------------------------
    | Even if enabled, capture is hard-disabled in production.
    */
    'enabled' => env('LIVEAPI_ENABLED', true),

    /*
    |--------------------------------------------------------------------------
    | Freeze Mode
    |--------------------------------------------------------------------------
    | When true, no new snapshots or schema changes are recorded.
    */
    'frozen' => env('LIVEAPI_FROZEN', false),

    /*
    |--------------------------------------------------------------------------
    | Storage
    |--------------------------------------------------------------------------
    */
    'storage_path' => storage_path('liveapi'),

    /*
    |--------------------------------------------------------------------------
    | Sensitive Fields Masking
    |--------------------------------------------------------------------------
    */
    'mask_fields' => [
        'password',
        'password_confirmation',
        'token',
        'card_number',
    ],
];
